workera: bundle exec ruby Interrogator.rb
workerb: bundle exec ruby Interrogated.rb
workerc: bundle exec ruby Judge.rb
workerd: bundle exec ruby Medium.rb
workere: bundle exec ruby Spirits.rb
workerf: bundle exec ruby Witch-1.rb
workerg: bundle exec ruby Witch-2.rb
workerh: bundle exec ruby Witch-3.rb
workeri: bundle exec ruby Witch-4.rb
workerj: bundle exec ruby Witch-5.rb